// <auto-generated />
namespace MovieCustomerWithAuthMVC_app.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addreleasedatecolinmovie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addreleasedatecolinmovie));
        
        string IMigrationMetadata.Id
        {
            get { return "202009021305478_add release date col in movie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
